title: Jeku
email: mike@skott.us
description: Jekyll + haiku = Jeku
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maskott.github.io/jeku/" # the base hostname & protocol for your site
twitter_username: maskott
github_username:  maskott
permalink: /:title
encoding: "utf-8"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
